name: Build and Push Docker Image on PR Close

on:
  pull_request_target:
    types: [closed]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.repository_owner }}/studyapp:${{ github.sha }}
